### ISSUE TITLE
'Feature toggle' for Transit

### ISSUE THREAD

**Issue by michaz** [matsim-org/josm-matsim-plugin#4]
I think we need something like a switch to turn off transit support completely while it is in development. So that when you turn it off, simple network editing works as before.

One does not always need this - it is completely OK, for example, if new features are not complete as long as the incomplete new feature does not do any harm. But at the moment, existing functionality has stopped working, so it should be possible to switch back to the way it was before.

**Comment by michaz** [comment]
(But perhaps we don't really need this after all. At least as long as we only edit imported networks, everything about transit should just be implicitly switched off by the fact that no TransitSchedule is there.)

**Comment by michaz** [comment]
Would it, for example, be possible to split "Import", so that I can import just a Network (and it works like before), *and then*, if I want to, I can load a TransitSchedule (with a different menu item)? If everything works as we think, it should be possible to load it incrementally, right?

**Comment by nkuehnel** [comment]
In the latter case we'd have to ensure that all referenced links from the stop facilities exist though. Since they are only identified by Id we had to check for the original Id of the links (or have them mapped otherwise). If we can do this, it shouldn't be a problem to load a schedule at any time. We then have to agree on what happens if a referenced link of a stop facility is not existing in the current network though. Should the facility be left out? Should the schedule fail to load? What happens if the schedule does not fit to the network? As far as i know there is currently no hint in the .xml transit schedule which implies a related network.

**Comment by nkuehnel** [comment]
This problem actually already exists if we load a schedule and network at the same time...

**Comment by michaz** [comment]
Perhaps a feature toggle is not so necessary anymore as soon as saving/loading of the TransitSchedule is separate.
