### ISSUE TITLE
Could not load plugin matsim

### ISSUE THREAD

**Issue by kainagel** [matsim-org/josm-matsim-plugin#62]
![untitled](https://user-images.githubusercontent.com/8777649/29984675-b1584258-8f5b-11e7-957f-99c0cc999daa.png)

No matter what I do (such as download the newest version of JOSM), I am getting the above.  Is this a bug, or should I do something different?  Thanks.

**Comment by nkuehnel** [comment]
Thanks for the hint!
Since we develop with the latest josm build, the plugin wrongly required a higher josm version which is not yet released. 
Should work now with the plugin latest release:
https://github.com/matsim-org/josm-matsim-plugin/releases/download/v0.8.2/matsim.jar

Also updated it on josms plugin site, make sure to use plugin version 0.8.2

Hope it works

**Comment by michaz** [comment]
Hmm, @nkuehnel, I think you got it the wrong way round: The plug-in correctly requires the new unreleased version (it doesn't work with the older one). What was missing was the information about _which older version_ would work with the older version of JOSM.

I think I got it now.

**Comment by michaz** [comment]
@kainagel This may require deleting your plug-in directory, because JOSM caches version information etc.

For me, it gets version 0.7.9 now and it works.

**Comment by nkuehnel** [comment]
Ah yes thanks For me, 0.8.2 also worked in latest published Release 12545

**Comment by michaz** [comment]
Hmpf. For me it crashed neck over head. ,-)

**Comment by michaz** [comment]
Thanks, everyone.
