### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/josm-matsim-plugin#67]
When running tests, the following exception occurs:
java.lang.SecurityException: class "org.openstreetmap.josm.tools.MemoryManagerTest"'s signer information does not match signer information of other classes in the same package

Is this somehow related to the new josm-unittest dependency, as it does not occur when it is not included? Can anyone help? @floscher @michaz

**Comment by floscher** [comment]
This is the same issue as JOSM/Mapillary#68.

It is caused indeed by the `josm-unittest´ dependency. That dependency is always compiled from the [source code of the unit tests](https://github.com/openstreetmap/josm/tree/mirror/test/unit) for the latest JOSM version.

Since JOSM version 13025 a new code signing certificate is used to sign the published *.jar files (see https://josm.openstreetmap.de/wiki/StartupPage). Because this plugin is compiled against [JOSM 12885](https://github.com/matsim-org/josm-matsim-plugin/blob/03f242967157cc5887629a083e59f93f5ce37069/build.gradle#L59), the `josm.jar` is signed with a different certificate than `josm-unittest.jar`.

Bumping the `josm.josmCompileVersion` to at least 13025 should make this exception go away.

**Comment by nkuehnel** [comment]
Very helpful, thanks for thorough explanation and quick response :)
